config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'students#index'
  resources :students
  # get 'pages/hello'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
# frozen_string_literal: true

class Student < ApplicationRecord
  validates :first_name, :last_name, :email, :address, :program, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def hello; end
end

app/controllers/students_controller.rb
# frozen_string_literal: true

class StudentsController < ApplicationController
  before_action :set_student, only:%i[show edit update destroy]
  # action for displaying all the students in the list
  def index
    @students = Student.all
  end

  # action for implementing the form
  def new
    @student = Student.new
  end

  # action for submitting and saving a student
  def create
    @student = Student.new(
      first_name: params[:student][:first_name],
      last_name: params[:student][:last_name],
      email: params[:student][:email],
      address: params[:student][:address],
      program: params[:student][:program]
    )
    if @student.save
      puts 'Student information saved'
      redirect_to students_path
    else
      render :new
    end
  end

  # action to display one student
  def show
    
  end

  def edit 
    
  end

  def update
    if @student.update(student_params)
      redirect_to student_path(@student)
    else 
      render :edit
    end
  end

  def destroy 
    @student.destroy
    redirect_to students_path
  end

  private

  # creating a seperate action for params using strong parameters
  def student_params
    params.require(:student).permit(:first_name, :last_name, :email, :address, :program)
  end

  #used this method to refactor my code , instead of the find in every method using the callback above
  def set_student
  #this is to find the student first
    @student = Student.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

# top level doc comment error solved
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hellorails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/hello.html.erb
<h1>Hello Rails</h1>

app/views/students/edit.html.erb
<h2>EDIT STUDENT INFORMATION</h2>

<!--form block -->
<%= form_with model: @student do |form| %>
<%if @student.errors.any?%>
    <%@student.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
  <% end %>
  <div>
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>
  <br>
  <div>
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>
  <br>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <br>
  <div>
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>
  <br>
  <div>
    <%= form.label :program %>
    <%= form.text_field :program %>
  </div>

  <br>
  <div>
    <%= form.submit %>
  </div>
<%end%>

<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>WELCOME TO RAILS</h1>

<%= link_to 'ADD A NEW STUDENT', new_student_path %>

<h2>Microverse Students List</h2>

<table>
 <thead>
   <tr>
      <th>first_name</th> 
      <th>last_name</th>
      <th>email</th>
      <th>address</th>
      <th>program</th>
      <th colspan="3">Actions</th>
    </tr>
 </thead>
 <tbody>
  <% @students.each do |student|%>
    <tr>
      <td><%= student.first_name%></td>
      <td><%= student.last_name%></td>
      <td><%= student.email%></td>
      <td><%= student.address%></td>
      <td><%= student.program%></td>
      </td>
      <td><%= link_to 'View details',student %></td>
      <td><%= link_to 'Edit details', edit_student_path(student) %></td>

      <!--DELETING IN RAILS 7-->
      <td><%= button_to 'Delete student', student, method: :delete , form: {data: {turbo_confirm: 'Are you sure you want to delete?'}}%></td>
    </tr>
  <% end %>
 </tbody>
</table>

app/views/students/new.html.erb
<h2>NEW STUDENT</h2>

<!--form block -->
<%= form_with model: @student do |form| %>
<!-- displaying error messages-->
  <%if @student.errors.any?%>
    <%@student.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
  <% end %>

  <div>
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>
  <br>
  <div>
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>
  <br>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <br>
  <div>
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>
  <br>
  <div>
    <%= form.label :program %>
    <%= form.text_field :program %>
  </div>

  <br>
  <div>
    <%= form.submit %>
  </div>
<%end%>

:

app/views/students/show.html.erb
<h1>Full student details</h1>

<p><strong>First Name: </strong><%= @student.first_name %></p>
<p><strong>Last Name: </strong><%= @student.last_name %></p>
<p><strong>Email: </strong><%= @student.email %></p>
<p><strong>Address: </strong><%= @student.address %></p>
<p><strong>Program: </strong><%= @student.program %></p>

<%= link_to 'Back to Homepage', students_path %> | <%= link_to 'Edit details', edit_student_path(@student) %>

<!--DELETING IN RAILS 7-->
<%= button_to 'Delete student', @student, method: :delete , form: {data: {turbo_confirm: 'Are you sure you want to delete?'}} %>